### PR TITLE
index.html: Update data URL to point at my collected 2015-04-09-UW-data

### PR DESCRIPTION
**Pull request by wking**
This is an alternative approach to the local URL approach taken in
761ea1a (update index.html with URLs to files for lesson data,
2015-04-06).  The downside of my approach is that there's a separate
repository (which we need for the archive link).  The upside is that
it's a single click download for all the lessons, and that it
preserves the current divergence between the R and Python data.

Sorry for the overlap Ben, but I hadn't realized you were taking a run
at this when I started working on it last night.  I'm not sure where
your R/Python zip is from, so I don't know if it's the current R data,
or the current Python data, or some older version of one or the other.
I'm using data from last night's tip for the central R and Python
lessons, but I'm not sure what our R and Python instructors are
planning on using.  Anyway, feel free to merge this or not depending
on what makes more sense to you ;).

### CODE REVIEW

**Comment by benmarwick** [comment]
Thanks, I got the shell, R and Python lesson data files from the swc novice repos yesterday, so I'm happy that they're up to date. 

We can't expect the students to use git to get these files because git is day two am, and they need the files from day one am, so best to keep it simple with zip downloads for everything.

**Comment by wking** [comment]
On Tue, Apr 07, 2015 at 11:22:54AM -0700, Ben Marwick wrote:

> Thanks, I got the shell, R and Python lesson data files from the swc
> novice repos yesterday, so I'm happy that they're up to date.

How did you resolve the differences in (for example)
inflammation-03.csv?

  $ diff -u <(cd python-novice-inflammation/data; sha1sum *) <(cd r-novice-inflammation/data; sha1sum *)
  --- /dev/fd/63  2015-04-07 14:29:04.911254415 -0700
  +++ /dev/fd/62  2015-04-07 14:29:04.911254415 -0700
  @@ -1,15 +1,18 @@
  +d6461edebdd6ee81e77a404e61b22b0e525f713b  car-speeds-cleaned.csv
  +d510316362af7120b7a674d4dda20a83a150f98d  car-speeds.csv
   55eb559be66b7e40040780fcc0923ea1e1193567  inflammation-01.csv
   e7fd9b6451133291f461a606c628c21256340967  inflammation-02.csv
  -b5ad680b72a515b4cb0170e6998d6d17308d2407  inflammation-03.csv
  +275696b5040652afbacc1ca1ac751aaa78a19a00  inflammation-03.csv
   6e63a1d61ce8fe4bdfaa71b73d296ca2bb8ce8f1  inflammation-04.csv
   95e478919b76113eeff58ec160c00afec103c0f7  inflammation-05.csv
   804e5774a77b947c7960adf6a416910de59e7ac4  inflammation-06.csv
   50f9b666e75f5376e6bb2d531f2fcdab588acab6  inflammation-07.csv
  -b5ad680b72a515b4cb0170e6998d6d17308d2407  inflammation-08.csv
  +85d562dddbd23e6ff279d62c74623b4859cad62f  inflammation-08.csv
   cc2ba28d4c1d5144704bce16cc51f907833fcd96  inflammation-09.csv
   0adff19a54b18deeaae8ccfe0865e7f206e28460  inflammation-10.csv
  -b5ad680b72a515b4cb0170e6998d6d17308d2407  inflammation-11.csv
  +6ccbb25a46648aafd287c2608ffd9fb665a96232  inflammation-11.csv
   63d4317161fa5e5d5c16074226fdee7ec6742c07  inflammation-12.csv
  +417649f5bea28e962f13fafc72b328dcb54a5091  sample.csv
   ac12803bbe561708f8c57ddf77caf44ebe87312e  small-01.csv
   5f3f5fa751dc4b19d5acb2de8e13d556f3c33abe  small-02.csv
   96fe56bb31aaaad6d6ad2d7d31a39372625f7527  small-03.csv

I haven't actually looked at the diffs, maybe the changes are just
whitespace?

> We can't expect the students to use git to get these files because
> git is day two am, and they need the files from day one am, so best
> to keep it simple with zip downloads for everything.

Which is why I link to the zip download [1](https://github.com/efran/2015-04-09-UW/pull/16/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR356) ;).

**Comment by benmarwick** [comment]
I haven't, I'm just going to assume for now that they're close enough. I'm out of time to investigate further. Did you see any major differences?

**Comment by wking** [comment]
On Tue, Apr 07, 2015 at 03:07:25PM -0700, Ben Marwick wrote:

> I haven't, I'm just going to assume for now that they're close
> enough. I'm out of time to investigate further. Did you see any
> major differences?

I didn't check to see what the differences were.  I just checked to
see if there were differences and though “I don't have time to look
into this for lessons I'm not teaching.  I'll just copy over both sets
of data”.  So we're in the same boat on time, and just have different
reactions to it.  If you prefer the “hope they're close enough”
approach (which I agree has good odds of being right), then feel free
to close this PR.

**Pull request closed without merging**
